### ISSUE TITLE
Using a path instead of a port for api server

### ISSUE THREAD

**Issue by lcasassa** [allegroai/trains-server#24]
Hi, I can only expose port 80 and 443(https). Port 8008 is not permitted because the way I have a kubernetes cluster set up. I can add rules by path or another subdomain for serving the api. But I see that there is no argument or environment variable to set the api url when running the web server (static files served with nginx). I would like to request having an environment variable or argument to update the api in the webserver. Or is there a work around on how to set up an ingress in kubernetes for trains?

Thanks for the great app!

**Comment by lcasassa** [comment]
So I manually added the port 8008 in the loadbalancer to point to the port 30008 on all nodes of the k8s cluster. That did the trick.

**Comment by lcasassa** [comment]
I would still be nice to be able to set a custom url for the trains api in the trains server.

**Comment by bmartinn** [comment]
Hi,

You can easily use trains-server with subdomains, by adding rules so that:

- app. domain is routed to kubernetes node on port 30080
- api. domain is routed to kubernetes node on port 30008
- files. domain is routed to kubernetes node on port 30081

Note that in order for the trains UI to be able to find the servers, your subdomains must be namedad shown above (`app` for webserver, `api` for apiserver and `files` for filesserver).

In order to use the trains python package with your server installation, you'll also need to make sure your `trains.conf` file contains the correct host name you've set for each component, for example:
```
api {
    web_server: "http://app.your.domain"
    api_server: "http://api.your.domain"
    files_server: "http://files.your.domain"
}
```

**Comment by lcasassa** [comment]
cool! thanks for letting me know.
