### ISSUE TITLE
Docker open ports

### ISSUE THREAD

**Issue by dinist** [allegroai/trains-server#38]
Hi,

I launched the trains-server using docker installation on my dedicated server with Ubuntu 18.04. Next day I noticed xmr miner on redis docker. Solved this problem by managing iptables.
Is there another way to secure installation?

**Comment by bmartinn** [comment]
Hi @dinist,

Nice job finding that miner :)

You can easily prevent external access the Redis, ElasticSearch and MongoDB dockers by simply removing the port mappings in the `docker-compose.yml` file.Simply remove the following lines for each service:
- Redis: [line 102](https://github.com/allegroai/trains-server/blob/bb3218f65d42d1b4be71f83e138235ff3ad70cd0/docker-compose.yml#L102) and [line 103](https://github.com/allegroai/trains-server/blob/bb3218f65d42d1b4be71f83e138235ff3ad70cd0/docker-compose.yml#L103)
- MongoDB: [line 91](https://github.com/allegroai/trains-server/blob/bb3218f65d42d1b4be71f83e138235ff3ad70cd0/docker-compose.yml#L91) and [line 92](https://github.com/allegroai/trains-server/blob/bb3218f65d42d1b4be71f83e138235ff3ad70cd0/docker-compose.yml#L92)
- ElasticSearch: [line 64](https://github.com/allegroai/trains-server/blob/bb3218f65d42d1b4be71f83e138235ff3ad70cd0/docker-compose.yml#L64) and [line 65](https://github.com/allegroai/trains-server/blob/bb3218f65d42d1b4be71f83e138235ff3ad70cd0/docker-compose.yml#L65)

Since all services use the `backend` internal docker network to access each other, these lines are optional and simply allow external access to these services.

Please note that we still advise you to make sure that the Trains Server is behind a firewall and/or access is via a VPN, since the Trains File Server ports are (and should be) open for external access and the Trains File Server will currently serve any request.

**Comment by dinist** [comment]
Thank you!
